# Production: main -> yarilomail.org
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yarilomail-web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yarilomail/website.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - ../helm_values/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yarilomail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Staging: develop -> wwwdev.yarilomail.org
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yarilomail-web-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yarilomail/website.git
    targetRevision: develop
    path: helm
    helm:
      valueFiles:
        - ../helm_values/values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yarilomail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
